spring:
  application:
    name: consumer
  rabbitmq:
    virtual-host: my_vhost
    host: 152.136.97.217
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #手动应答机制
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true

server:
  port: 13003
